server:
  port: 8082

spring:
  application:
    name: orquestrador

  datasource:
    url: jdbc:h2:mem:orquestrador_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    topic:
      start:
        cadastroJuridico: cadastro-juridico-start


#logging:
#  file:
#    name: ../logs/${spring.application.name}.log
#    path: ../logs
#  level:
#    root: INFO