server:
  port: 8080

spring:
  application:
    name: orquestrador

  datasource:
    url: jdbc:h2:mem:orquestrador_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

kafka:
  topic:
    command:
      register:
        seller: saga.epic.seller.command.register
        store: saga.epic.store.command.register
        financial: saga.epic.financial.command.register
      compensate:
        seller: saga.epic.seller.command.compensate
        store: saga.epic.store.command.compensate
        financial: saga.epic.financial.command.compensate
    event:
      success:
        seller: saga.epic.seller.event.register.success
        store: saga.epic.store.event.register.success
        financial: saga.epic.financial.event.register.success
      failed:
        seller: saga.epic.seller.event.register.failed
        store: saga.epic.store.event.register.failed
        financial: saga.epic.financial.event.register.failed
